/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './apps/admin/src/**/*.{html,ts}',
    './apps/waiter/src/**/*.{html,ts}',
    './libs/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#9d4300',
        'primary-container': '#f97316',
        secondary: '#575e70',
        'secondary-container': '#d9dff5',
        tertiary: '#006398',
        'tertiary-container': '#00a2f4',
        surface: '#f9f9ff',
        'surface-dim': '#d3daea',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eefe',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'surface-variant': '#dce2f3',
        background: '#f9f9ff',
        'on-background': '#151c27',
        'on-surface': '#151c27',
        'on-surface-variant': '#584237',
        'on-primary': '#ffffff',
        'on-primary-container': '#582200',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5c6274',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#003554',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#8c7164',
        'outline-variant': '#e0c0b1',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        'inverse-primary': '#ffb690',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
}
